version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nfts4h-platform
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: scripts/reload-app.sh
      timeout: 300
      runas: ubuntu