name: CI/CD

on:
  push:
    branches:
      - testing_deployment

jobs:
  prepEnvironment:
    name: Preparing Environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12.x']
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified    

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        node-version: ['12.x']
        appname: ['nfts4h-staging']
        deploy-group: ['staging']
        s3-bucket: ['nfts4h-staging-deployments']
        s3-filename: ['deployment-${{ github.sha }}']

    needs: prepEnvironment
    steps:
      - uses: actions/checkout@v2      

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Deploy push to AWS S3
      - name: AWS Deploy push
        run: |
          aws deploy push \
            --application-name ${{ matrix.appname }} \
            --description "This is a revision for the ${{ matrix.appname }}-${{ github.sha }}" \
            --ignore-hidden-files \
            --s3-location s3://${{ matrix.s3-bucket }}/${{ matrix.s3-filename }}.zip \
            --source . \

      # Create deployment to CodeDeploy
      - name: AWS Create Deployment
        run: |
          aws deploy create-deployment \
            --application-name ${{ matrix.appname }} \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name ${{ matrix.deploy-group }} \
            --file-exists-behavior OVERWRITE \
            --s3-location bucket=${{ matrix.s3-bucket }},key=${{ matrix.s3-filename }}.zip,bundleType=zip \